vim.cmd.colorscheme("gruvbox")
vim.api.nvim_set_hl(0, "LineNr", { fg = "#D1D1D1" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#ffa13d" })
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#5C534F", fg = "NONE" })

vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#1d2b21", fg = "#a9b665" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#2b1d1d", fg = "#ea6962" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#1d1d2b", fg = "#d8a657" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#44475a", fg = "#ffffff" })
